######## New MorphoDynamX session v2.0 r2-793: 2024-07-16 12:19:05
Process.Stack__System__Import('', 'Main', '0', 'Yes')
Process.Mesh__Creation__Mesh_Cutting_Surface()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Structure__Subdivide()
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Signal__Smooth_Mesh_Signal('3', '')
Process.Stack__System__Import('', 'Main', '0', 'Yes')
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Signal__Smooth_Mesh_Signal('3', '')
Process.Stack__System__Import('', 'Main', '0', 'Yes')
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Signal__Smooth_Mesh_Signal('3', '')
Process.Stack__System__Import('', 'Main', '0', 'Yes')
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Signal__Smooth_Mesh_Signal('3', '')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__Segmentation__Watershed_Segmentation('50000', 'Yes', '')
######## New MorphoDynamX session v2.0 r2-793: 2024-07-16 13:06:59
Process.Stack__System__Import('', 'Main', '0', 'Yes')
Process.Mesh__Creation__Mesh_Cutting_Surface()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Structure__Subdivide()
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Signal__Smooth_Mesh_Signal('3', '')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__Segmentation__Watershed_Segmentation('50000', 'Yes', '')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/test.mdxm', 'No', 'No', '0')
Process.Mesh__Segmentation__Watershed_Segmentation('50000', 'Yes', '')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/test.mdxm', 'No', 'No', '0')
Process.Mesh__System__Save('/home/marco/trabajo/Models/RootModel/Hook/test.mdxm', 'No', '0')
Process.Mesh__Segmentation__Watershed_Segmentation('50000', 'Yes', '')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/test.mdxm', 'No', 'No', '0')
Process.Mesh__System__Save('/home/marco/trabajo/Models/RootModel/Hook/test.mdxm', 'No', '0')
Process.Mesh__Segmentation__Watershed_Segmentation('50000', 'Yes', '')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/test.mdxm', 'No', 'No', '0')
Process.Mesh__System__Save('/home/marco/trabajo/Models/RootModel/Hook/test.mdxm', 'No', '0')
Process.Mesh__Segmentation__Watershed_Segmentation('50000', 'Yes', '')
Process.Mesh__System__Delete_Selection('Yes', 'All')
Process.Mesh__System__Save('/home/marco/trabajo/Models/RootModel/Hook/test.mdxm', 'No', '0')
Process.Tools__Cell_Maker__Mesh_2D__Tools__Polygonize_Triangles('-1.0')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/test2.mdxm', 'No', 'No', '0')
Process.Tools__Cell_Maker__Mesh_2D__Tools__Polygonize_Triangles('0')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__System__Save('/home/marco/trabajo/Models/RootModel/Hook/test2.mdxm', 'No', '0')
######## New MorphoDynamX session v2.0 r2-793: 2024-07-16 14:31:58
Process.Stack__System__Import('', 'Main', '0', 'Yes')
Process.Mesh__Creation__Mesh_Cutting_Surface()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide()
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Stack__System__Import('', 'Main', '0', 'Yes')
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Structure__Subdivide()
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__System__Delete_Cell_Complex('Surface')
Process.Stack__System__Import('', 'Main', '0', 'Yes')
Process.Mesh__Creation__Mesh_Cutting_Surface()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide_Bisect_Triangle('0.0')
Process.Mesh__Structure__Subdivide_Bisect_Triangle('0.0')
Process.Mesh__Structure__Subdivide_Bisect_Wedge('0.0')
Process.Mesh__Structure__Subdivide_Triangles()
Process.Mesh__Structure__Subdivide_Triangles()
Process.Mesh__Structure__Subdivide_Triangles()
Process.Mesh__System__Delete_Cell_Complex('Surface')
Process.Mesh__Creation__Mesh_Cutting_Surface()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Structure__Subdivide()
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Signal__Smooth_Mesh_Signal('3', '')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__Segmentation__Watershed_Segmentation('50000', 'Yes', '')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/A.mdxm', 'No', 'No', '0')
Process.Mesh__System__Save('/home/marco/trabajo/Models/RootModel/Hook/A.mdxm', 'No', '0')
Process.Mesh__Segmentation__Watershed_Segmentation('50000', 'Yes', '')
Process.Mesh__System__Delete_Selection('Yes', 'All')
Process.Tools__Cell_Maker__Mesh_2D__Tools__Polygonize_Triangles('0')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/A.mdxm', 'No', 'No', '0')
Process.Tools__System__Load_View('')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/Hook_final.mdxm', 'no', 'no', '0')
Process.Mesh__System__Export('/home/marco/trabajo/Models/RootModel/Hook/Hook_final.mdxm', 'Text', 'No', '0')
######## New MorphoDynamX session v2.0 r2-793: 2024-07-30 12:30:55
Process.Mesh__System__Import('0', '', 'Imported', 'No', 'No')
