######## New MorphoDynamX session v2.0 r2-793: 2024-07-16 12:19:05
Process.Stack__System__Import('', 'Main', '0', 'Yes')
Process.Mesh__Creation__Mesh_Cutting_Surface()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Structure__Subdivide()
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Signal__Smooth_Mesh_Signal('3', '')
Process.Stack__System__Import('', 'Main', '0', 'Yes')
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Signal__Smooth_Mesh_Signal('3', '')
Process.Stack__System__Import('', 'Main', '0', 'Yes')
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Signal__Smooth_Mesh_Signal('3', '')
Process.Stack__System__Import('', 'Main', '0', 'Yes')
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Signal__Smooth_Mesh_Signal('3', '')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__Segmentation__Watershed_Segmentation('50000', 'Yes', '')
######## New MorphoDynamX session v2.0 r2-793: 2024-07-16 13:06:59
Process.Stack__System__Import('', 'Main', '0', 'Yes')
Process.Mesh__Creation__Mesh_Cutting_Surface()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Structure__Subdivide()
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Signal__Smooth_Mesh_Signal('3', '')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__Segmentation__Watershed_Segmentation('50000', 'Yes', '')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/test.mdxm', 'No', 'No', '0')
Process.Mesh__Segmentation__Watershed_Segmentation('50000', 'Yes', '')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/test.mdxm', 'No', 'No', '0')
Process.Mesh__System__Save('/home/marco/trabajo/Models/RootModel/Hook/test.mdxm', 'No', '0')
Process.Mesh__Segmentation__Watershed_Segmentation('50000', 'Yes', '')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/test.mdxm', 'No', 'No', '0')
Process.Mesh__System__Save('/home/marco/trabajo/Models/RootModel/Hook/test.mdxm', 'No', '0')
Process.Mesh__Segmentation__Watershed_Segmentation('50000', 'Yes', '')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/test.mdxm', 'No', 'No', '0')
Process.Mesh__System__Save('/home/marco/trabajo/Models/RootModel/Hook/test.mdxm', 'No', '0')
Process.Mesh__Segmentation__Watershed_Segmentation('50000', 'Yes', '')
Process.Mesh__System__Delete_Selection('Yes', 'All')
Process.Mesh__System__Save('/home/marco/trabajo/Models/RootModel/Hook/test.mdxm', 'No', '0')
Process.Tools__Cell_Maker__Mesh_2D__Tools__Polygonize_Triangles('-1.0')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/test2.mdxm', 'No', 'No', '0')
Process.Tools__Cell_Maker__Mesh_2D__Tools__Polygonize_Triangles('0')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__System__Save('/home/marco/trabajo/Models/RootModel/Hook/test2.mdxm', 'No', '0')
######## New MorphoDynamX session v2.0 r2-793: 2024-07-16 14:31:58
Process.Stack__System__Import('', 'Main', '0', 'Yes')
Process.Mesh__Creation__Mesh_Cutting_Surface()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide()
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Stack__System__Import('', 'Main', '0', 'Yes')
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Structure__Subdivide()
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__System__Delete_Cell_Complex('Surface')
Process.Stack__System__Import('', 'Main', '0', 'Yes')
Process.Mesh__Creation__Mesh_Cutting_Surface()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide_Bisect_Triangle('0.0')
Process.Mesh__Structure__Subdivide_Bisect_Triangle('0.0')
Process.Mesh__Structure__Subdivide_Bisect_Wedge('0.0')
Process.Mesh__Structure__Subdivide_Triangles()
Process.Mesh__Structure__Subdivide_Triangles()
Process.Mesh__Structure__Subdivide_Triangles()
Process.Mesh__System__Delete_Cell_Complex('Surface')
Process.Mesh__Creation__Mesh_Cutting_Surface()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Structure__Subdivide()
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Structure__Subdivide()
Process.Mesh__Signal__Project_Signal('-1', '1', 'No', '0.0', '60000.0', 'Signal')
Process.Mesh__Signal__Smooth_Mesh_Signal('3', '')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__Segmentation__Watershed_Segmentation('50000', 'Yes', '')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/A.mdxm', 'No', 'No', '0')
Process.Mesh__System__Save('/home/marco/trabajo/Models/RootModel/Hook/A.mdxm', 'No', '0')
Process.Mesh__Segmentation__Watershed_Segmentation('50000', 'Yes', '')
Process.Mesh__System__Delete_Selection('Yes', 'All')
Process.Tools__Cell_Maker__Mesh_2D__Tools__Polygonize_Triangles('0')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Mesh('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__Structure__Smooth_Border('1')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/A.mdxm', 'No', 'No', '0')
Process.Tools__System__Load_View('')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/Hook_final.mdxm', 'no', 'no', '0')
Process.Mesh__System__Export('/home/marco/trabajo/Models/RootModel/Hook/Hook_final.mdxm', 'Text', 'No', '0')
######## New MorphoDynamX session v2.0 r2-793: 2024-07-30 12:30:55
Process.Mesh__System__Import('0', '', 'Imported', 'No', 'No')
######## New MorphoDynamX session v2.0 r2-793: 2024-08-20 13:58:39
Process.Tools__System__Save_View('/home/marco/trabajo/Models/RootModel/test_180.mdxv')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/test_180_test1.mdxm', 'no', 'no', '0')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Mesh__System__Save('/home/marco/trabajo/Models/RootModel/test_180.mdxm', 'no', '0')
Process.Tools__System__Save_View('/home/marco/trabajo/Models/RootModel/Hook/test_180_test1.mdxv')
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/Hook/test_180_test2.mdxv')
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/Hook/test_180_test1.mdxv')
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/Hook/test_180_test2.mdxv')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/test_180_test1.mdxm', 'no', 'no', '0')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__02_Remesh('False', 'Hard', '3', 'Model/Root/03 Cell Tissue', 'Model/Root/Triangulate Faces', 'Model/Root/ClearCells', 'Mesh/Structure/Split Edges', 'Tools/Cell Maker/Mesh 2D/Tools/Polygonize Triangles')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__22_Set_Cell_Attr('Cortex', '1', '0', '-1', 'False', '-1', '0,-1,0', '0.01,0,0')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__22_Set_Cell_Attr('Cortex', '1', '0', '-1', 'False', '-1', '0,-0.01,0', '0.01,0,0')
Process.Model__Root__22_Set_Cell_Attr('Cortex', '1', '0', '-1', 'False', '-1', '0,-0.01,0', '1,0,0')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__22_Set_Cell_Attr('Cortex', '1', '0', '-1', 'False', '-1', '0,-0.01,0', '1,0,0')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__22_Set_Cell_Attr('Cortex', '1', '0', '-1', 'False', '-1', '0,-0.01,0', '1,0,0')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__22_Set_Cell_Attr('Cortex', '1', '0', '-1', 'False', '-1', '0,-0.01,0', '1,0,0')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__22_Set_Cell_Attr('Cortex', '1', '0', '-1', 'False', '-1', '0,-0.01,0', '1,0,0')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Mesh__System__Save('/home/marco/trabajo/Models/RootModel/test_180.mdxm', 'no', '0')
Process.Tools__System__Save_View('/home/marco/trabajo/Models/RootModel/Hook/test_180_test1.mdxv')
######## New MorphoDynamX session v2.0 r2-793: 2024-08-21 13:23:19
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/test_180.mdxv')
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/Hook/test_180_test2.mdxv')
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/Hook/test_180_test3.mdxv')
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/Hook/test_180_test1.mdxv')
######## New MorphoDynamX session v2.0 r2-793: 2024-08-21 14:10:04
Process.Tools__System__Save_View('/home/marco/trabajo/Models/RootModel/test_____.mdxv')
Process.Mesh__System__Save('/home/marco/trabajo/Models/RootModel/test______.mdxm', 'no', '0')
######## New MorphoDynamX session v2.0 r2-793: 2024-08-21 15:25:49
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/test_180.mdxv')
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/Hook/test_180_test4.mdxv')
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/Hook/test_180_test3.mdxv')
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/Hook/test_180_test2.mdxv')
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/Hook/test_180_test1.mdxv')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/test______.mdxm', 'no', 'no', '0')
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/Hook/test_180_test4.mdxv')
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/Hook/test_180_test4.mdxv')
######## New MorphoDynamX session v2.0 r2-793: 2024-08-21 15:38:04
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/test.mdxv')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/test_180_test3.mdxm', 'no', 'no', '0')
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/Hook/test_180_test3.mdxv')
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/Hook/test_180_test1.mdxv')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/test______.mdxm', 'no', 'no', '0')
######## New MorphoDynamX session v2.0 r2-793: 2024-08-21 15:41:26
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/test_180.mdxv')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/test_180_test3.mdxm', 'no', 'no', '0')
######## New MorphoDynamX session v2.0 r2-793: 2024-08-21 15:41:53
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/test_180.mdxv')
Process.Model__Root__22_Set_Cell_Attr('Cortex', '1', '0', '-1', 'False', '-1', '0,0,0', '0,0,0')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Mesh__System__Save('/home/marco/trabajo/Models/RootModel/test______.mdxm', 'no', '0')
Process.Mesh__System__Load('/home/marco/trabajo/Models/RootModel/Hook/test_180_test4.mdxm', 'no', 'no', '0')
######## New MorphoDynamX session v2.0 r2-793: 2024-08-21 15:52:47
Process.Tools__System__Load_View('/home/marco/trabajo/Models/RootModel/test_180.mdxv')
Process.Model__Root__22_Set_Cell_Attr('Cortex', '1', '0', '-1', 'False', '-1', '0,0,0', '0,0,0')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
Process.Model__Root__22_Set_Cell_Attr('LRC', '1', '0', '-1', 'False', '-1', '0,0,0', '0,0,0')
Process.Model__Root__01_Root('1', '1', 'True', 'False', 'True', 'True', 'Soft', '0', '5', '0', 'Test', 'True', 'debug.csv', '0,0', 'Model/Root/23 Set Global Attr', '0,0', '10000', 'mesh.mdxm', 'Model/Root/03 Cell Tissue', 'Model/Root/051 Mechanical Solver', 'Model/Root/05 Mechanics', 'Model/Root/052 Mechanical Growth', 'Model/Root/06 Chemicals', 'Model/Root/061 Chemicals Solver', 'Model/Root/04 Divide Cells', 'Model/Root/31 Delete Cell', 'Model/Root/4 Execute Test', 'Model/Root/Triangulate Faces', 'Model/Root/02 Remesh', 'Model/Root/Remesh Cell', 'Mesh/Structure/Split Edges', 'Tools/System/Save View', 'Mesh/System/Save')
